site_name: Portal Acadêmico
site_description: Portal Acadêmico da Profª Me. Thissiany Almeida
site_author: Profª Me. Thissiany Almeida

theme:
  name: material
  language: pt-BR

  custom_dir: overrides

  palette:

    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Tema escuro

    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Tema claro

  features:

    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top

    - search.suggest
    - search.highlight
    - search.share

    - content.code.copy
    - content.tabs.link

plugins:
  - search

extra_css:
  - assets/stylesheets/extra.css

extra:
  generator: false

markdown_extensions:

  - admonition

  - attr_list

  - md_in_html

  - tables

  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.tabbed:
      alternate_style: true
  
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:

  - Início: index.md

  - Sobre: sobre.md

  - Contato: contato.md

  - Disciplinas:

      - Algoritmos e Lógica de Programação: disciplinas/alp/index.md

      - Aprendizagem de Máquina: disciplinas/am/index.md

      - Estrutura de Dados: disciplinas/ed/index.md

      - Matemática para Computação: disciplinas/mc/index.md

      - Métodos para Produção do Conhecimento: disciplinas/mpc/index.md

      - Processamento de Linguagem Natural: disciplinas/pln/index.md